# Generated by Django 3.2.5 on 2021-07-27 13:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etech', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, null=True, verbose_name='Image'),
        ),
    ]
